// START_MODULE_CONTRACT
//   PURPOSE: Schema-reference rendering from live grammar inventories
//   SCOPE: Registered shape registry and markdown/explain section rendering
//   DEPENDS: none
//   LINKS: M-GRAMMAR
//   ROLE: RUNTIME
//   MAP_MODE: EXPORTS
// END_MODULE_CONTRACT
//
// START_MODULE_MAP
//   SCHEMA_SHAPE_REGISTRY
//   isRegisteredSchemaShape
//   renderSchemaReference
//   renderSchemaShape
// END_MODULE_MAP
import { GRAMMAR_INVENTORIES } from "./grammar";

const GENERATED_BANNER = "<!-- Generated. Do not edit this file by hand. -->";

const REGISTERED_SHAPE_NAMES = [
  "artifact-root",
  "root-metadata",
  "change-status",
  "change-spec",
  "change-plan",
  "change-task",
  "assertion",
  "durable-scope",
  "observed-write-scope",
  "anchor-family",
  "context-artifact",
  "ledger-verdict",
  "gate-decision",
  "clarification",
  "design-reference",
] as const;

type BarrelKey = keyof typeof GRAMMAR_INVENTORIES;
type RegisteredShapeName = (typeof REGISTERED_SHAPE_NAMES)[number];

export const SCHEMA_SHAPE_REGISTRY: Record<RegisteredShapeName, readonly BarrelKey[]> = {
  "artifact-root": ["STANDARD_ROOT_TAGS", "CHANGE_ROOT_TAGS"],
  "root-metadata": ["ROOT_METADATA_ATTRIBUTE", "CHANGE_ROOT_METADATA_ATTRIBUTES"],
  "change-status": ["VALID_CHANGE_STATUSES"],
  "change-spec": ["SPEC_REQUIRED_SECTIONS"],
  "change-plan": ["PLAN_REQUIRED_SECTIONS"],
  "change-task": ["TASK_REQUIRED_SECTIONS"],
  assertion: ["ASSERTION_SECTION_TAGS"],
  "durable-scope": ["DURABLE_SCOPE_DIRECT_TAGS"],
  "observed-write-scope": ["OBSERVED_SCOPE_DIRECT_TAGS"],
  "anchor-family": ["ANCHOR_FAMILIES"],
  "context-artifact": ["CONTEXT_ARTIFACTS"],
  "ledger-verdict": ["REVIEW_VERDICT_OUTCOMES"],
  "gate-decision": ["GATE_DECISION_GATES", "GATE_DECISION_VALUES"],
  clarification: ["CLARIFICATION_WORKING_FORM"],
  "design-reference": ["DESIGN_REFERENCE_CHILD_TAGS"],
};

export function isRegisteredSchemaShape(token: string): boolean {
  return Object.hasOwn(SCHEMA_SHAPE_REGISTRY, token);
}

function membersOf(value: unknown): string[] {
  if (typeof value === "string") {
    return [value];
  }
  if (value instanceof Set) {
    return [...value].map(String);
  }
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      if (typeof item === "string") {
        return [item];
      }
      if (item && typeof item === "object") {
        return Object.values(item).filter((field): field is string => typeof field === "string");
      }
      return [];
    });
  }
  return [];
}

export function renderSchemaShape(name: string): string {
  const keys = isRegisteredSchemaShape(name)
    ? SCHEMA_SHAPE_REGISTRY[name as RegisteredShapeName]
    : undefined;
  const members = keys ? keys.flatMap((key) => membersOf(GRAMMAR_INVENTORIES[key])) : [];
  return [`## ${name}`, "", ...members.map((member) => `- ${member}`)].join("\n");
}

export function renderSchemaReference(): string {
  const preamble = [
    "Coverage is the registered shapes listed here, and those inventories only.",
    "",
    `Registered shapes: ${REGISTERED_SHAPE_NAMES.join(", ")}.`,
    "",
    "This document is not a complete schema. This document is not a complete grammar.",
    "",
    "Excluded classes:",
    "- Imperative validators in grammar.ts.",
    "- File-local markup families. graph-module and module-contract are file-local markup, not members of this registry.",
    "",
    "Whole-segment ** matches zero or more path segments, so web/js/**/*.js matches web/js/app.js.",
  ].join("\n");

  const sections = REGISTERED_SHAPE_NAMES.map((name) => renderSchemaShape(name));
  return [GENERATED_BANNER, "", preamble, "", ...sections].join("\n") + "\n";
}
