import { describe, expect, it } from "bun:test";

import { GRAMMAR_INVENTORIES, validateArtifactRoot, validateChangeArtifact } from "./grammar";
import {
  isRegisteredSchemaShape,
  renderSchemaReference,
  renderSchemaShape,
  SCHEMA_SHAPE_REGISTRY,
} from "./schema-reference";
import { parseGraceXmlArtifact } from "./xml";

const SET_PROBE_SENTINEL = "NgraceProbeSentinelRoot";
const ARRAY_PROBE_SENTINEL = "ProbeSentinelSection";

const GENERATED_BANNER = "<!-- Generated. Do not edit this file by hand. -->";

const REGISTERED_SHAPES = [
  "artifact-root",
  "root-metadata",
  "change-status",
  "change-spec",
  "change-plan",
  "change-task",
  "assertion",
  "durable-scope",
  "observed-write-scope",
  "anchor-family",
  "context-artifact",
  "ledger-verdict",
  "gate-decision",
  "clarification",
  "design-reference",
] as const;

const REGISTERED_SHAPES_SENTENCE = `Registered shapes: ${REGISTERED_SHAPES.join(", ")}.`;
const COVERAGE_SENTENCE = "Coverage is the registered shapes listed here, and those inventories only.";
const NOT_COMPLETE_SCHEMA = "This document is not a complete schema.";
const NOT_COMPLETE_GRAMMAR = "This document is not a complete grammar.";
const EXCLUDED_VALIDATORS = "- Imperative validators in grammar.ts.";
const EXCLUDED_FILE_LOCAL =
  "- File-local markup families. graph-module and module-contract are file-local markup, not members of this registry.";
const EXCLUDED_GLOB =
  "- Glob matching: P1.4 asked for zero-depth globstar. F60 blocks documenting it while two implementations disagree.";

const DOCUMENTED_F60_PAIR = ["web/js/**/*.js", "web/js/app.js"] as const;
const UNDOCUMENTED_F60_PAIRS = ["src/**/*.ts", "src/a.ts", "src/x/a.ts", "src/**"] as const;

const GLOB_RULE =
  "Whole-segment ** matches zero or more path segments, so web/js/**/*.js matches web/js/app.js.";

function validSpec(changeId = "C-EXAMPLE"): string {
  return `<NgraceChangeSpec graceVersion="1.0" status="approved"><${changeId}><Summary>Summary.</Summary><Goals><Goal>Goal.</Goal></Goals><Constraints><Constraint>Constraint.</Constraint></Constraints><NonGoals><NonGoal>Non-goal.</NonGoal></NonGoals><AcceptanceCriteria><Criterion>Accepted.</Criterion></AcceptanceCriteria><AffectedAreas><M-EXAMPLE /></AffectedAreas><VerificationIntent><ExpectedCommand>bun test</ExpectedCommand></VerificationIntent></${changeId}></NgraceChangeSpec>`;
}

function liveMemberTexts(value: unknown): string[] {
  if (typeof value === "string") {
    return [value];
  }
  if (value instanceof Set) {
    return [...value].map(String);
  }
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      if (typeof item === "string") {
        return [item];
      }
      if (item && typeof item === "object") {
        return Object.values(item).filter((field): field is string => typeof field === "string");
      }
      return [];
    });
  }
  return [];
}

describe("AC-REFERENCE-GENERATED", () => {
  it("exports GRAMMAR_INVENTORIES and the renderer functions", () => {
    expect(GRAMMAR_INVENTORIES).toBeDefined();
    expect(typeof GRAMMAR_INVENTORIES).toBe("object");
    expect(typeof renderSchemaReference).toBe("function");
    expect(typeof renderSchemaShape).toBe("function");
    expect(typeof isRegisteredSchemaShape).toBe("function");
    expect(SCHEMA_SHAPE_REGISTRY).toBeDefined();
  });

  it("proves barrel properties are the live validator bindings and reverts in finally", () => {
    const tags = GRAMMAR_INVENTORIES.STANDARD_ROOT_TAGS;
    expect(tags instanceof Set).toBe(true);
    const tagSet = tags as Set<string>;
    const tagSizeBefore = tagSet.size;

    try {
      tagSet.add(SET_PROBE_SENTINEL);
      const probed = validateArtifactRoot(
        parseGraceXmlArtifact("probe.xml", `<${SET_PROBE_SENTINEL} graceVersion="1.0" />`),
      );
      expect(probed.issues.some((issue) => issue.code === "artifact.invalid-root-tag")).toBe(false);
    } finally {
      tagSet.delete(SET_PROBE_SENTINEL);
      expect(tagSet.size).toBe(tagSizeBefore);
    }

    const rejected = validateArtifactRoot(
      parseGraceXmlArtifact("probe.xml", `<${SET_PROBE_SENTINEL} graceVersion="1.0" />`),
    );
    expect(rejected.issues.some((issue) => issue.code === "artifact.invalid-root-tag")).toBe(true);

    const sections = GRAMMAR_INVENTORIES.SPEC_REQUIRED_SECTIONS as unknown as string[];
    expect(Array.isArray(sections)).toBe(true);
    const sectionSizeBefore = sections.length;

    try {
      sections.push(ARRAY_PROBE_SENTINEL);
      const probed = validateChangeArtifact(parseGraceXmlArtifact("spec.xml", validSpec()), "active");
      expect(
        probed.issues.some(
          (issue) => issue.code === "change.spec-missing-section" && issue.message.includes(ARRAY_PROBE_SENTINEL),
        ),
      ).toBe(true);
    } finally {
      const index = sections.lastIndexOf(ARRAY_PROBE_SENTINEL);
      if (index !== -1) {
        sections.splice(index, 1);
      }
      expect(sections.length).toBe(sectionSizeBefore);
    }

    const restored = validateChangeArtifact(parseGraceXmlArtifact("spec.xml", validSpec()), "active");
    expect(
      restored.issues.some(
        (issue) => issue.code === "change.spec-missing-section" && issue.message.includes(ARRAY_PROBE_SENTINEL),
      ),
    ).toBe(false);
  });

  it("interpolates every live inventory member into the generated reference", () => {
    const generated = renderSchemaReference();
    expect(typeof generated).toBe("string");
    expect(generated.length).toBeGreaterThan(0);

    for (const value of Object.values(GRAMMAR_INVENTORIES)) {
      for (const member of liveMemberTexts(value)) {
        expect(generated).toContain(member);
      }
    }

    expect(renderSchemaShape("change-spec")).toContain("Summary");
    expect(renderSchemaShape("assertion")).toContain("MustExist");
  });
});

describe("AC-COVERAGE-NAMED", () => {
  it("starts with the generated banner then a preamble that names coverage and exclusions", () => {
    const generated = renderSchemaReference();
    const lines = generated.split("\n");
    expect(lines[0]).toBe(GENERATED_BANNER);

    const firstShapeIndex = generated.indexOf("\n## ");
    expect(firstShapeIndex).toBeGreaterThan(0);
    const preamble = generated.slice(0, firstShapeIndex);

    expect(preamble).toContain(COVERAGE_SENTENCE);
    expect(preamble).toContain(REGISTERED_SHAPES_SENTENCE);
    expect(preamble).toContain(NOT_COMPLETE_SCHEMA);
    expect(preamble).toContain(NOT_COMPLETE_GRAMMAR);
    expect(preamble).toContain(EXCLUDED_VALIDATORS);
    expect(preamble).toContain(EXCLUDED_FILE_LOCAL);
    expect(preamble).not.toContain(EXCLUDED_GLOB);

    for (const shape of REGISTERED_SHAPES) {
      expect(preamble).toContain(shape);
    }

    expect(preamble).not.toMatch(/(?<!not )a complete schema/);
    expect(preamble).not.toMatch(/(?<!not )a complete grammar/);
  });
});

describe("AC-NO-GLOB-RULE", () => {
  it("registers no glob or globstar shape and prints no globstar match-outcome table", () => {
    const registryKeys = Object.keys(SCHEMA_SHAPE_REGISTRY);
    expect(registryKeys.some((key) => /glob/i.test(key))).toBe(false);
    for (const shape of REGISTERED_SHAPES) {
      expect(isRegisteredSchemaShape(shape)).toBe(true);
    }
    expect(isRegisteredSchemaShape("glob")).toBe(false);
    expect(isRegisteredSchemaShape("globstar")).toBe(false);

    const generated = renderSchemaReference();
    const firstShapeIndex = generated.indexOf("\n## ");
    expect(firstShapeIndex).toBeGreaterThan(0);
    const afterPreamble = generated.slice(firstShapeIndex);
    expect(afterPreamble).not.toMatch(/glob matching/i);
    expect(afterPreamble).not.toMatch(/globstar/i);

    for (const pair of UNDOCUMENTED_F60_PAIRS) {
      expect(generated).not.toContain(pair);
    }
    expect(generated).not.toContain("review false");
    expect(generated).not.toContain("review true");
    expect(generated).not.toContain("scope true");
  });
});

describe("C-ONE-GLOB-LANGUAGE T-002 glob-doc", () => {
  it("glob-doc: preamble no longer contains the F60 exclusion sentence", () => {
    const generated = renderSchemaReference();
    const firstShapeIndex = generated.indexOf("\n## ");
    expect(firstShapeIndex).toBeGreaterThan(0);
    const preamble = generated.slice(0, firstShapeIndex);
    expect(preamble).not.toContain(EXCLUDED_GLOB);
  });

  it("glob-doc: preamble states the zero-or-more-segment rule and the F60 pair", () => {
    const generated = renderSchemaReference();
    const firstShapeIndex = generated.indexOf("\n## ");
    expect(firstShapeIndex).toBeGreaterThan(0);
    const preamble = generated.slice(0, firstShapeIndex);
    expect(preamble).toContain(GLOB_RULE);
    expect(preamble).toContain(DOCUMENTED_F60_PAIR[0]);
    expect(preamble).toContain(DOCUMENTED_F60_PAIR[1]);
  });
});
